spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-9geeprfi.sql.tencentcdb.com:26708/springboot_demo
    username: root
    password: Q9BFzqAx
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost