spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bupthotel
    username: root
    password: 1234
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8000
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost